# DO NOT DELETE

src/birthdeath.o: /usr/include/math.h /usr/include/features.h
src/birthdeath.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/birthdeath.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/birthdeath.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/birthdeath.o: /usr/include/bits/mathcalls.h src/Tree.h
src/birthdeath.o: /usr/include/stdlib.h /usr/include/sys/types.h
src/birthdeath.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/birthdeath.o: /usr/include/time.h /usr/include/endian.h
src/birthdeath.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/birthdeath.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/birthdeath.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/birthdeath.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/birthdeath.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/birthdeath.o: /usr/include/_G_config.h /usr/include/wchar.h
src/birthdeath.o: /usr/include/bits/stdio_lim.h
src/birthdeath.o: /usr/include/bits/sys_errlist.h /usr/include/assert.h
src/birthdeath.o: /usr/include/string.h src/ExtendArray.h src/phylogeny.h
src/birthdeath.o: src/HashTable.h src/birthdeath.h src/spidir.h
src/branch_prior.o: /usr/include/stdlib.h /usr/include/features.h
src/branch_prior.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/branch_prior.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/branch_prior.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/branch_prior.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/branch_prior.o: /usr/include/endian.h /usr/include/bits/endian.h
src/branch_prior.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/branch_prior.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/branch_prior.o: /usr/include/sys/sysmacros.h
src/branch_prior.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/branch_prior.o: /usr/include/stdio.h /usr/include/libio.h
src/branch_prior.o: /usr/include/_G_config.h /usr/include/wchar.h
src/branch_prior.o: /usr/include/bits/stdio_lim.h
src/branch_prior.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/branch_prior.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/branch_prior.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/branch_prior.o: src/common.h /usr/include/string.h src/ExtendArray.h
src/branch_prior.o: src/branch_prior.h src/Tree.h src/spidir.h
src/branch_prior.o: src/birthdeath.h src/phylogeny.h src/HashTable.h
src/branch_prior.o: src/seq_likelihood.h
src/common.o: /usr/include/assert.h /usr/include/features.h
src/common.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/common.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/common.o: /usr/include/math.h /usr/include/bits/huge_val.h
src/common.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/common.o: /usr/include/stdlib.h /usr/include/sys/types.h
src/common.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/common.o: /usr/include/time.h /usr/include/endian.h
src/common.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/common.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/common.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/common.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/common.o: /usr/include/stdio.h /usr/include/libio.h
src/common.o: /usr/include/_G_config.h /usr/include/wchar.h
src/common.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
src/common.o: /usr/include/string.h src/common.h src/ExtendArray.h
src/matlab_interface.o: src/matlab_interface.h
src/maxml.o: /usr/include/libgen.h /usr/include/features.h
src/maxml.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/maxml.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/maxml.o: /usr/include/stdlib.h /usr/include/sys/types.h
src/maxml.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/maxml.o: /usr/include/time.h /usr/include/endian.h
src/maxml.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/maxml.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/maxml.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/maxml.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/maxml.o: /usr/include/stdio.h /usr/include/libio.h
src/maxml.o: /usr/include/_G_config.h /usr/include/wchar.h
src/maxml.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
src/maxml.o: src/common.h /usr/include/math.h /usr/include/bits/huge_val.h
src/maxml.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/maxml.o: /usr/include/assert.h /usr/include/string.h src/ExtendArray.h
src/maxml.o: src/phylogeny.h src/Tree.h src/HashTable.h src/parsimony.h
src/maxml.o: src/search.h src/spidir.h src/Matrix.h src/ConfigParam.h
src/maxml.o: src/Sequences.h
src/mem.o: src/Stack.h src/ExtendArray.h /usr/include/assert.h
src/mem.o: /usr/include/features.h /usr/include/sys/cdefs.h
src/mem.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/mem.o: /usr/include/gnu/stubs-32.h
src/parsimony.o: /usr/include/assert.h /usr/include/features.h
src/parsimony.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/parsimony.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/parsimony.o: /usr/include/math.h /usr/include/bits/huge_val.h
src/parsimony.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/parsimony.o: /usr/include/stdlib.h /usr/include/sys/types.h
src/parsimony.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/parsimony.o: /usr/include/time.h /usr/include/endian.h
src/parsimony.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/parsimony.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/parsimony.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/parsimony.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/parsimony.o: /usr/include/stdio.h /usr/include/libio.h
src/parsimony.o: /usr/include/_G_config.h /usr/include/wchar.h
src/parsimony.o: /usr/include/bits/stdio_lim.h
src/parsimony.o: /usr/include/bits/sys_errlist.h /usr/include/string.h
src/parsimony.o: src/common.h src/ExtendArray.h src/spidir.h src/parsimony.h
src/parsimony.o: src/Tree.h
src/phylogeny.o: src/phylogeny.h src/Tree.h /usr/include/stdlib.h
src/phylogeny.o: /usr/include/features.h /usr/include/sys/cdefs.h
src/phylogeny.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/phylogeny.o: /usr/include/gnu/stubs-32.h /usr/include/sys/types.h
src/phylogeny.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/phylogeny.o: /usr/include/time.h /usr/include/endian.h
src/phylogeny.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/phylogeny.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/phylogeny.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/phylogeny.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/phylogeny.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/phylogeny.o: /usr/include/_G_config.h /usr/include/wchar.h
src/phylogeny.o: /usr/include/bits/stdio_lim.h
src/phylogeny.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/phylogeny.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/phylogeny.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/phylogeny.o: /usr/include/string.h src/ExtendArray.h src/HashTable.h
src/phylogeny.o: src/Matrix.h
src/search.o: src/common.h /usr/include/stdlib.h /usr/include/features.h
src/search.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/search.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/search.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/search.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/search.o: /usr/include/endian.h /usr/include/bits/endian.h
src/search.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/search.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/search.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
src/search.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/libio.h
src/search.o: /usr/include/_G_config.h /usr/include/wchar.h
src/search.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
src/search.o: /usr/include/math.h /usr/include/bits/huge_val.h
src/search.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/search.o: /usr/include/assert.h /usr/include/string.h src/ExtendArray.h
src/search.o: src/Matrix.h src/phylogeny.h src/Tree.h src/HashTable.h
src/search.o: src/branch_prior.h src/spidir.h src/birthdeath.h
src/search.o: src/parsimony.h src/search.h src/seq_likelihood.h
src/seq_likelihood.o: /usr/include/math.h /usr/include/features.h
src/seq_likelihood.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/seq_likelihood.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/seq_likelihood.o: /usr/include/bits/huge_val.h
src/seq_likelihood.o: /usr/include/bits/mathdef.h
src/seq_likelihood.o: /usr/include/bits/mathcalls.h /usr/include/time.h
src/seq_likelihood.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/seq_likelihood.o: src/common.h /usr/include/stdlib.h
src/seq_likelihood.o: /usr/include/sys/types.h /usr/include/endian.h
src/seq_likelihood.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/seq_likelihood.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/seq_likelihood.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/seq_likelihood.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/seq_likelihood.o: /usr/include/stdio.h /usr/include/libio.h
src/seq_likelihood.o: /usr/include/_G_config.h /usr/include/wchar.h
src/seq_likelihood.o: /usr/include/bits/stdio_lim.h
src/seq_likelihood.o: /usr/include/bits/sys_errlist.h /usr/include/assert.h
src/seq_likelihood.o: /usr/include/string.h src/ExtendArray.h src/Matrix.h
src/seq_likelihood.o: src/seq_likelihood.h src/Tree.h src/parsimony.h
src/seq_likelihood.o: src/spidir.h
src/Sequences.o: src/spidir.h src/Sequences.h src/common.h
src/Sequences.o: /usr/include/stdlib.h /usr/include/features.h
src/Sequences.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/Sequences.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/Sequences.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/Sequences.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/Sequences.o: /usr/include/endian.h /usr/include/bits/endian.h
src/Sequences.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/Sequences.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/Sequences.o: /usr/include/sys/sysmacros.h
src/Sequences.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/Sequences.o: /usr/include/stdio.h /usr/include/libio.h
src/Sequences.o: /usr/include/_G_config.h /usr/include/wchar.h
src/Sequences.o: /usr/include/bits/stdio_lim.h
src/Sequences.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/Sequences.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/Sequences.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/Sequences.o: /usr/include/string.h src/ExtendArray.h
src/spidir.o: src/spidir.h src/phylogeny.h src/Tree.h /usr/include/stdlib.h
src/spidir.o: /usr/include/features.h /usr/include/sys/cdefs.h
src/spidir.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/spidir.o: /usr/include/gnu/stubs-32.h /usr/include/sys/types.h
src/spidir.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/spidir.o: /usr/include/time.h /usr/include/endian.h
src/spidir.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/spidir.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/spidir.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/spidir.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/spidir.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/spidir.o: /usr/include/_G_config.h /usr/include/wchar.h
src/spidir.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
src/spidir.o: /usr/include/math.h /usr/include/bits/huge_val.h
src/spidir.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/spidir.o: /usr/include/assert.h /usr/include/string.h src/ExtendArray.h
src/spidir.o: src/HashTable.h
src/spidir_main.o: /usr/include/libgen.h /usr/include/features.h
src/spidir_main.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/spidir_main.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/spidir_main.o: /usr/include/stdlib.h /usr/include/sys/types.h
src/spidir_main.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/spidir_main.o: /usr/include/time.h /usr/include/endian.h
src/spidir_main.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/spidir_main.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/spidir_main.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/spidir_main.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/spidir_main.o: /usr/include/stdio.h /usr/include/libio.h
src/spidir_main.o: /usr/include/_G_config.h /usr/include/wchar.h
src/spidir_main.o: /usr/include/bits/stdio_lim.h
src/spidir_main.o: /usr/include/bits/sys_errlist.h src/common.h
src/spidir_main.o: /usr/include/math.h /usr/include/bits/huge_val.h
src/spidir_main.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/spidir_main.o: /usr/include/assert.h /usr/include/string.h
src/spidir_main.o: src/ExtendArray.h src/phylogeny.h src/Tree.h
src/spidir_main.o: src/HashTable.h src/parsimony.h src/search.h src/spidir.h
src/spidir_main.o: src/Matrix.h src/ConfigParam.h src/Sequences.h
src/Tree.o: /usr/include/assert.h /usr/include/features.h
src/Tree.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/Tree.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/Tree.o: /usr/include/stdio.h /usr/include/bits/types.h
src/Tree.o: /usr/include/bits/typesizes.h /usr/include/libio.h
src/Tree.o: /usr/include/_G_config.h /usr/include/wchar.h
src/Tree.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
src/Tree.o: src/Tree.h /usr/include/stdlib.h /usr/include/sys/types.h
src/Tree.o: /usr/include/time.h /usr/include/endian.h
src/Tree.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/Tree.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/Tree.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/Tree.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/Tree.o: src/common.h /usr/include/math.h /usr/include/bits/huge_val.h
src/Tree.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/Tree.o: /usr/include/string.h src/ExtendArray.h src/Matrix.h
src/birthdeath.o: src/Tree.h /usr/include/stdlib.h /usr/include/features.h
src/birthdeath.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/birthdeath.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/birthdeath.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/birthdeath.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/birthdeath.o: /usr/include/endian.h /usr/include/bits/endian.h
src/birthdeath.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/birthdeath.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/birthdeath.o: /usr/include/sys/sysmacros.h
src/birthdeath.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/birthdeath.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/birthdeath.o: /usr/include/_G_config.h /usr/include/wchar.h
src/birthdeath.o: /usr/include/bits/stdio_lim.h
src/birthdeath.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/birthdeath.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/birthdeath.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/birthdeath.o: /usr/include/string.h src/ExtendArray.h src/spidir.h
src/branch_prior.o: src/Tree.h /usr/include/stdlib.h /usr/include/features.h
src/branch_prior.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/branch_prior.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/branch_prior.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/branch_prior.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/branch_prior.o: /usr/include/endian.h /usr/include/bits/endian.h
src/branch_prior.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/branch_prior.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/branch_prior.o: /usr/include/sys/sysmacros.h
src/branch_prior.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/branch_prior.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/branch_prior.o: /usr/include/_G_config.h /usr/include/wchar.h
src/branch_prior.o: /usr/include/bits/stdio_lim.h
src/branch_prior.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/branch_prior.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/branch_prior.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/branch_prior.o: /usr/include/string.h src/ExtendArray.h src/spidir.h
src/branch_prior.o: src/birthdeath.h
src/common.o: /usr/include/stdlib.h /usr/include/features.h
src/common.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/common.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/common.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/common.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/common.o: /usr/include/endian.h /usr/include/bits/endian.h
src/common.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/common.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/common.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
src/common.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/libio.h
src/common.o: /usr/include/_G_config.h /usr/include/wchar.h
src/common.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
src/common.o: /usr/include/math.h /usr/include/bits/huge_val.h
src/common.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/common.o: /usr/include/assert.h /usr/include/string.h src/ExtendArray.h
src/ConfigParam.o: /usr/include/libgen.h /usr/include/features.h
src/ConfigParam.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/ConfigParam.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/ConfigParam.o: /usr/include/stdlib.h /usr/include/sys/types.h
src/ConfigParam.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/ConfigParam.o: /usr/include/time.h /usr/include/endian.h
src/ConfigParam.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/ConfigParam.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/ConfigParam.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/ConfigParam.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/ConfigParam.o: /usr/include/stdio.h /usr/include/libio.h
src/ConfigParam.o: /usr/include/_G_config.h /usr/include/wchar.h
src/ConfigParam.o: /usr/include/bits/stdio_lim.h
src/ConfigParam.o: /usr/include/bits/sys_errlist.h
src/ExtendArray.o: /usr/include/assert.h /usr/include/features.h
src/ExtendArray.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/ExtendArray.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/Matrix.o: /usr/include/stdio.h /usr/include/features.h
src/Matrix.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/Matrix.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/Matrix.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/Matrix.o: /usr/include/libio.h /usr/include/_G_config.h
src/Matrix.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
src/Matrix.o: /usr/include/bits/sys_errlist.h
src/mem.o: src/Stack.h src/ExtendArray.h /usr/include/assert.h
src/mem.o: /usr/include/features.h /usr/include/sys/cdefs.h
src/mem.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/mem.o: /usr/include/gnu/stubs-32.h
src/parsimony.o: src/Tree.h /usr/include/stdlib.h /usr/include/features.h
src/parsimony.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/parsimony.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/parsimony.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/parsimony.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/parsimony.o: /usr/include/endian.h /usr/include/bits/endian.h
src/parsimony.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/parsimony.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/parsimony.o: /usr/include/sys/sysmacros.h
src/parsimony.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/parsimony.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/parsimony.o: /usr/include/_G_config.h /usr/include/wchar.h
src/parsimony.o: /usr/include/bits/stdio_lim.h
src/parsimony.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/parsimony.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/parsimony.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/parsimony.o: /usr/include/string.h src/ExtendArray.h
src/phylogeny.o: src/Tree.h /usr/include/stdlib.h /usr/include/features.h
src/phylogeny.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/phylogeny.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/phylogeny.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/phylogeny.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/phylogeny.o: /usr/include/endian.h /usr/include/bits/endian.h
src/phylogeny.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/phylogeny.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/phylogeny.o: /usr/include/sys/sysmacros.h
src/phylogeny.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/phylogeny.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/phylogeny.o: /usr/include/_G_config.h /usr/include/wchar.h
src/phylogeny.o: /usr/include/bits/stdio_lim.h
src/phylogeny.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/phylogeny.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/phylogeny.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/phylogeny.o: /usr/include/string.h src/ExtendArray.h src/HashTable.h
src/search.o: src/spidir.h
src/seq_likelihood.o: src/Tree.h /usr/include/stdlib.h
src/seq_likelihood.o: /usr/include/features.h /usr/include/sys/cdefs.h
src/seq_likelihood.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/seq_likelihood.o: /usr/include/gnu/stubs-32.h /usr/include/sys/types.h
src/seq_likelihood.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/seq_likelihood.o: /usr/include/time.h /usr/include/endian.h
src/seq_likelihood.o: /usr/include/bits/endian.h /usr/include/sys/select.h
src/seq_likelihood.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/seq_likelihood.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/seq_likelihood.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/seq_likelihood.o: src/common.h /usr/include/stdio.h /usr/include/libio.h
src/seq_likelihood.o: /usr/include/_G_config.h /usr/include/wchar.h
src/seq_likelihood.o: /usr/include/bits/stdio_lim.h
src/seq_likelihood.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/seq_likelihood.o: /usr/include/bits/huge_val.h
src/seq_likelihood.o: /usr/include/bits/mathdef.h
src/seq_likelihood.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/seq_likelihood.o: /usr/include/string.h src/ExtendArray.h
src/Sequences.o: src/common.h /usr/include/stdlib.h /usr/include/features.h
src/Sequences.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/Sequences.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/Sequences.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/Sequences.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/Sequences.o: /usr/include/endian.h /usr/include/bits/endian.h
src/Sequences.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/Sequences.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/Sequences.o: /usr/include/sys/sysmacros.h
src/Sequences.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
src/Sequences.o: /usr/include/stdio.h /usr/include/libio.h
src/Sequences.o: /usr/include/_G_config.h /usr/include/wchar.h
src/Sequences.o: /usr/include/bits/stdio_lim.h
src/Sequences.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/Sequences.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/Sequences.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/Sequences.o: /usr/include/string.h src/ExtendArray.h
src/Stack.o: src/ExtendArray.h /usr/include/assert.h /usr/include/features.h
src/Stack.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/Stack.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/Tree.o: /usr/include/stdlib.h /usr/include/features.h
src/Tree.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
src/Tree.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
src/Tree.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/Tree.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/Tree.o: /usr/include/endian.h /usr/include/bits/endian.h
src/Tree.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/Tree.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/Tree.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
src/Tree.o: /usr/include/alloca.h src/common.h /usr/include/stdio.h
src/Tree.o: /usr/include/libio.h /usr/include/_G_config.h
src/Tree.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
src/Tree.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
src/Tree.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
src/Tree.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
src/Tree.o: /usr/include/string.h src/ExtendArray.h
